FROM whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6-mcore0.12.0-te2.3

#     install EFA driver:
ENV NCCL_VERSION=2.25.1-1
ENV DEBIAN_FRONTEND=noninteractive
ENV EFA_INSTALLER_VERSION=1.40.0
ENV FI_EFA_SET_CUDA_SYNC_MEMOPS=0
ENV FI_PROVIDER=efa

RUN apt update && apt install -y linux-image-generic libhwloc-dev

RUN cd /tmp && \
    ldconfig && \

# NCCL EFA Plugin
RUN cd /tmp && \
    ./autogen.sh && \
    --with-cuda=/usr/local/cuda \
    make -j$(nproc) install && \

# NCCL
RUN echo "/usr/local/lib"      >> /etc/ld.so.conf.d/local.conf && \
    ldconfig

ENV OMPI_MCA_pml=^cm,ucx            \
    OMPI_MCA_btl=tcp,self           \
    FI_EFA_USE_HUGE_PAGE=0

